### PR TITLE
fix(security): clear 12 osv-scan advisories blocking the merge queue

### LINKED ISSUE #854: Re-evaluate brace-expansion GHSA-3jxr ignore once the fix stops breaking @eslint/config-array
## Context

`osv-scanner.toml` ignores **GHSA-3jxr-9vmj-r5cp** (`brace-expansion`) as build/test-tooling-only. This issue tracks the conditions under which the ignore must be revisited, so the suppression carries a contract (same spirit as our No-Untracked-Skips policy) instead of living forever unattended.

## Why it's ignored today (PR #853)

- **0 occurrences in the production dependency tree** — `pnpm list brace-expansion --prod` is empty for both the root and `@pinchy/web`. It only enters the lockfile via glob/minimatch under eslint, vitest and other build/test tooling, so it ships to no user.
- The GHSA-3jxr fix (`brace-expansion@5.0.7`) **breaks `@eslint/config-array`** (`expand is not a function`) at lint time, so bumping it is currently worse than useless. Our existing override only reaches `>=5.0.6`, one below the fix.

## Revisit when EITHER

1. `@eslint/config-array` (or whatever pulls the vulnerable `brace-expansion`) is compatible with `brace-expansion@>=5.0.7` — then bump the override to the fixed floor and drop the ignore, **or**
2. `brace-expansion` ever appears in the production tree (`--prod` list becomes non-empty) — an osv ignore is global and unscoped, so this would silently suppress a real production advisory. Treat that as a red flag and fix, don't extend the ignore.

## Acceptance

- Ignore for GHSA-3jxr-9vmj-r5cp removed from `osv-scanner.toml` (with the override raised to the fixed version), and `osv-scanner` still exits 0.

### PR DESCRIPTION
**Pull request by clemenshelm**
## What

Follow-up to #853 (merged). #853 unblocked the merge queue but deliberately
**ignored** the `brace-expansion` advisory GHSA-3jxr — its `5.0.7` fix broke
`@eslint/config-array` (`expand is not a function`) — and tracked the real fix
in #854. This PR **is** that fix, rebased onto main so the diff is only the delta.

## Changes (on top of merged #853)

**1. brace-expansion GHSA-3jxr — fixed for real, not ignored**

Raised the overrides to the fixed floors, **major-bounded** so each major stays
in its own lane:

| selector | → |
|---|---|
| `brace-expansion@>=1.0.0 <1.1.16` | `>=1.1.16 <2` |
| `brace-expansion@>=2.0.0 <2.1.2` | `>=2.1.2 <3` |
| `brace-expansion@>=5.0.0 <5.0.7` | `>=5.0.7 <6` |

Why this avoids the break #854/#853 hit: `@eslint/config-array` →
`minimatch@3.1.5` → `brace-expansion@1.1.16` (the fixed **v1** line, unchanged
export shape). `5.0.7` is pulled only by `minimatch@10.2.5` consumers
(`@typescript-eslint/typescript-estree`, openclaw) that tolerate it. The
`expand is not a function` error came from dragging config-array's v1 across a
major to 5.x; the major-bounded overrides never do that. The `osv-scanner.toml`
ignore for GHSA-3jxr is removed.

**2. astro osv triage — hardened**

Added `ignoreUntil = 2026-10-21` to the three residual astro ignores so the
exception can't outlive #851 silently, and grounded each reason in the
advisories' real scope: all three are XSS bugs upstream scopes to on-demand SSR
/ the dev server only — Starlight emits static HTML, so the built-and-deployed
docs site is unaffected regardless of the deferred Astro 7 major.

## Not re-touched

Everything #853 already landed — astro 6.4.8, body-parser 2.3.0, js-yaml 4.3.0,
protobufjs 8.7.1, and the openclaw unused-ignore cleanup — is inherited from
main and does not appear in this diff.

## Verification

- `pnpm install --frozen-lockfile`: lockfile up to date
- brace-expansion resolves to 1.1.16 / 2.1.2 / 5.0.7; `@eslint/config-array`
  stays on the fixed v1 (1.1.16)
- `osv-scanner.toml` parses; prettier clean
- Full CI (lint / typecheck / test / osv-scan) runs on this branch

Closes #854

### CODE REVIEW

**Comment by clemenshelm** [comment]
Superseded by main's consolidated OSV fix (`12accd496` + `40544662e`), which landed in parallel and is **more correct**: it discovered that bumping `brace-expansion` to 5.0.7 breaks `@eslint/config-array`, so it ignores that advisory (tracked in #854) instead of forcing the bump as this PR did. Main already covers all 12 advisories — same body-parser/js-yaml/protobufjs overrides, same docs astro→6.4.8, same 3 astro IgnoredVulns pointing at #851 (this PR's tracking issue, now in use). Closing as redundant; nothing here to salvage.

**Comment by clemenshelm** [comment]
Superseded by #857 — same branch (`security/osv-transitive-bumps`), rebased onto main after #853 merged (couldn't be reopened once the history was rewritten). #857 carries the real brace-expansion fix (closes #854) plus the astro `ignoreUntil` hardening.
